#ifndef NODE_TYPE_H
#define NODE_TYPE_H

// ===== AST 노드 정의 =====
enum class NodeType {
    PROGRAM, VARIABLE_DECLARATION, FUNCTION_DECLARATION,
    BLOCK_STATEMENT, IF_STATEMENT, WHILE_STATEMENT, FOR_STATEMENT,
    RETURN_STATEMENT, EXPRESSION_STATEMENT,
    BINARY_EXPRESSION, UNARY_EXPRESSION, CALL_EXPRESSION,
    IDENTIFIER, INTEGER_LITERAL, FLOAT_LITERAL, STRING_LITERAL,
    CHAR_LITERAL, BOOL_LITERAL, ASSIGNMENT_EXPRESSION,
    NAMESPACE_DECLARATION, IMPORT_STATEMENT
};
#endif // NODE_TYPE_H